### ISSUE TITLE
Feature: mail threading

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#253]
This is the only feature I miss from my mutt. So I decided to implement it.

This issue is to discuss all relevant decisions about mail threading.

**Comment by fischerling** [comment]
I have a working Threader implementing the threading algorithm from
Jamie Zawinsky. A description can be found here:
https://www.jwz.org/doc/threading.html

I tested it on the mailinglists I have subscribed and it produces the same
results as my mutt with one difference. Mutt collects mails with the same
Message-ID and presents them as the same message. My threader just uses the
last one he parses. But give you access to all not reachable messages through
the table `threader.overridden`.

To test the threader change the mailbox in sample.lua/threader.lua and run it.

## TODO

- [ ] Format the code to match the rest of the project. (needs #252)
- [ ] Implement the integration into lumail2.
- [ ] Maybe some caching ?

## Integration

The threader uses a tree datastructure with a container around our normal
CMessage objects so we can't just use the threads like our message table.

Some possibilities I have in mind:

+ A new index mode only for threads. Introduce a config value to decide which index mode to use.
    + This would make dealing with the datastructure from the threader easy.
    + We could easily add functions which operate on threads. (mark thread as
    read e.g.)
    + But this would also add a lot of new code
+ Just think of the threads as a sorting. Make a flat container table out of
    our sorted threads. Let the container expose all functionality of its message
    so you can use both the same way.
    + Then we have to hack the representation of the threads into the format
    cache or something.
    + Mail threading would share a  lot of code with the normal sorting.
+ Make all functions aware of threading.
    + I see a lot of work and bugs!


In my opinion the first one is the best.

What do you think ? Are you even interested in such a feature ?

**Comment by skx** [comment]
> What do you think ? Are you even interested in such a feature ?

Yes.

I cannot express my surprise an appreciation highly enough.  __You did good__.  I'm grateful.  I look forward to seeing this included in the next release.

I'll have to look at the WIP patch properly and think about it, but I'd be tempted to go the second route.  ("Just think of the threads as a sorting.")

I think you're right to pause though, because once you have threading you naturally want to operate upon threads (delete/mark-read/mark-unread/others?).  I think my immediate reaction is "If you have threading, which users will expect, why expose anything else?"

That might mean that we just drop `index.sort` entirely, and  _only_ show messages in a threaded view.  Is there any downside to that?  (Other than dropping features, obviously.)

**Comment by fischerling** [comment]
Thanks. It is the first "real" thing I do in lua.

I don't know how many prefer a non threaded mailbox over a threaded one.
But I know that in nearly all mail clients I used in the past (thunderbird,
evolution, mutt) threading was not the default.

Working on threads is not that hard even with a flat list because the tree is
double linked. So finding the rest of a thread if you know one message isn't
complicated.

**Comment by jugglerchris** [comment]
In my implementation of threading I haven't got around to publishing (sorry!), I did it as a custom sorting order. I'm not sure it makes sense to sort threads/subthreads by anything other than date.

**Comment by skx** [comment]
> I did it as a custom sorting order.

I assumed that would be how it would be done too, but I never quite dared start the project because I assumed it would be pretty complex.

**Comment by fischerling** [comment]
I think for the sorting of the siblings in a subthread only `Date` is really
useful. But sorting threads by their `From` field makes sense as well.

**Comment by skx** [comment]
You're right I think.

I expect the default view will probably be "threads + date", but allowing "thread + from" is probably required too.

**Comment by skx** [comment]
This was closed in #254.
